import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
        // Removed navbar header:
        <header className="bg-gray-100 p-4">
          <nav className="container mx-auto flex space-x-4">
            <Link href="/">
              Home
            </Link>
            <Link href="/login">
              Login
            </Link>
            <Link href="/revision">
              Revision Mode
            </Link>
          </nav>
        </header>
        */}
        {children}
      </body>
    </html>
  );
}